# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 509cd155f9a2002dc60677f9da502430cf4a7e7f307a31a1099ac37909005264909c6a3d915fc4384bed30848e400d9c9620c681d3ff9e72b7b9e1b97843845a

test:
  secret_key_base: f970d7ae751ceb01b19a4695272eec11f7aec8844dad8ed8bd9c0d21195650eec1a92ad18f800d6e9339e83a5fea3cb809ca8f23b1ea6cbf7d824e401451cef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
